# XX: uniform naming
# component | submodule-path | image | version-source
codeql-base    submodules/mrva-docker/base mrva-base        CODEQL_BASE_VERSION
gh-mrva        submodules/gh-mrva        mrva-gh-mrva        MRVA_VERSION
mrvaserver     submodules/mrvaserver     mrva-server         MRVA_VERSION
mrvaagent      submodules/mrvaagent      mrva-agent          MRVA_VERSION
mrvahepc       submodules/mrvahepc       mrva-hepc-container MRVA_VERSION
vscode         submodules/mrva-docker/containers/vscode code-server-initialized MRVA_VERSION
